# This workflow will install Python dependencies, run tests and lint with a single version of Python
# Fmor more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI
#To trigger the CI on events
on:
  push:
    branches:
        -main
  pull_request:
    branches:
        -main


jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest
